package org.datastructure.com;
import java.io.Console;
//import java.io.Console;
import java.util.List;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;
//import java.util.Vector;

//import javax.jws.Oneway;
//import javax.swing.table.DefaultTableModel;

//import com.ibm.icu.impl.locale.AsciiUtil;


public class ListHouse extends javax.swing.JDialog {
	
	/*String  FirstNameLH;
	String  lastNameLH;
	String  lotNumberLH;
	String  priceLH;
	String  squareFeetLH;
	String  numberOfBedRoomsLH;*/
	
	public ListHouse(java.awt.Frame parent, boolean modal,List<House> houses){
		  super(parent, modal);
		//houses = new House().readFile();
		initComponents();
		setLocationRelativeTo(null);
        
        SortedList sl = new SortedList();
        sl.setHouses(houses);
        houses = sl.getShortHouses();
        
        House hr = new House();
        hr.saveHouseList(houses);
        
        //houses = houses.sort();
        //System.clearProperty(Console);
        /*for(House h: houses )
        {
        	System.out.println(h.getLotNumber() + "\t" + h.getFirstName() + "\t" + h.getLastName() + "\t" + h.getNumberOfBedRooms() + "\t" + h.getPrice() + "\t" + h.getSquareFeet());
        }
        */
        
        DefaultTableModel df;
        df = (DefaultTableModel) jTable1.getModel();
        
        for(House h: houses){
            Vector v = new Vector();
            v.add(h.getLotNumber());// + "");
            v.add(h.getFirstName());
            v.add(h.getLastName());// + "");
            v.add(h.getPrice());//+ "");
            v.add(h.getSquareFeet());// + "");
            v.add(h.getNumberOfBedRooms());// + "");
            //System.out.println(v.firstElement());
            df.addRow(v);
        }
        
	}
	
	
	
	

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
	
	
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lot Number", "First Name", "Last Name", "Price", "Square Feet", "No of Bedrooms"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        pack();
        
    }

    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	/*
	
	
	public ListHouse (String FirstNameLH,String  lastNameLH,String  lotNumberLH,String  priceLH,String  squareFeetLH,String  numberOfBedRoomsLH) {
		
		this.FirstNameLH = FirstNameLH;
		this.lastNameLH = lastNameLH;
		this.lotNumberLH = lotNumberLH;
		this.priceLH = priceLH;
		this.squareFeetLH = squareFeetLH;
		this.numberOfBedRoomsLH = numberOfBedRoomsLH;
	}
	
		public ListHouse copy() {
			
			ListHouse result = new ListHouse(FirstNameLH, lastNameLH, lotNumberLH, priceLH, squareFeetLH, numberOfBedRoomsLH);
			return result;
			
		}
		*/
}
